version: '3'
services:
  web:
    build: .
    expose:
      - "8080"
    env_file:
      - .env
    ports:
      - "7777:8080"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    command: gunicorn -b 0.0.0.0:8080 --reload git_gateway.app:app
