version: '3'

services:
  redis:
    restart: unless-stopped
    env_file:
      - .env
    image: redis:6.0.5-alpine
    volumes:
      - ${REDIS_VOLUME}
    ports:
      - ${REDIS_PORT_MAP}
    container_name: ${REDIS_CONTAINER_NAME}

  mongodb:
    image: mongo:4.4.0-rc10-bionic
    container_name: ${MONGO_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${MONGO_PORT_MAP}
    env_file:
      - .env
    volumes:
      - ${MONGO_VOLUME}

  web:
    build: .
    restart: unless-stopped
    expose:
      - ${API_EXPOSED_PORT}
    env_file:
      - .env
    ports:
      - ${API_LOCAL_PORT}:${API_EXPOSED_PORT}
    links:
      - redis
      - mongodb
    volumes:
      - .:/git_gateway
    command: gunicorn -b 0.0.0.0:${API_EXPOSED_PORT} --reload git_gateway.app:app

volumes:
  redis: {}